version: "3"

services:
  app:
    container_name: api-docker-mongo
    restart: always
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - database
    links:
      - database
    volumes:
      - .:/usr/src/app
  database:
    container_name: mydatabase
    image: mongo
    ports:
      - "27017:27017"